//
//  Content.swift
//  Portfolio
//
//  Single source of truth for all personal content — mirrors Web/src/data/content.js.
//

import Foundation

// MARK: - Types

struct Profile {
    let name: String
    let title: String
    let tagline: String
    let location: String
    let email: String
    let github: URL?
    let linkedin: URL?
}

struct Education: Identifiable {
    let id = UUID()
    let school: String
    let degree: String
    let period: String
}

struct AboutInfo {
    let bio: [String]
    let education: [Education]
}

struct ExperienceItem: Identifiable {
    let id = UUID()
    let role: String
    let company: String
    let period: String
    let location: String
    let bullets: [String]
}

struct Project: Identifiable {
    let id = UUID()
    let name: String
    let description: String
    let tech: [String]
    let githubUrl: URL?
    let appStoreUrl: URL?
    let appStoreStatus: String?
}

struct Skill: Identifiable {
    let id = UUID()
    let name: String
    /// 0–100, drives bubble size in the skills field.
    let level: Double
}

struct SkillCategory: Identifiable {
    let id = UUID()
    let category: String
    let items: [Skill]
}

/// The five orbiting sections of the hub.
enum PortfolioSection: String, CaseIterable, Identifiable {
    case about, experience, projects, skills, contact

    var id: String { rawValue }

    var label: String {
        switch self {
        case .about: "About"
        case .experience: "Experience"
        case .projects: "Projects"
        case .skills: "Skills"
        case .contact: "Contact"
        }
    }

    var icon: String {
        switch self {
        case .about: "person.fill"
        case .experience: "briefcase.fill"
        case .projects: "shippingbox.fill"
        case .skills: "bolt.fill"
        case .contact: "paperplane.fill"
        }
    }
}

// MARK: - Content

enum Content {
    static let profile = Profile(
        name: "Vasileios Gkoumas",
        title: "iOS Developer",
        tagline: "I build delightful, performant iOS apps with Swift & SwiftUI — obsessed with clean design and smooth experiences.",
        location: "Athens, Greece",
        email: "vgkoumas@icloud.com",
        github: URL(string: "https://github.com/YungN3O"),
        linkedin: URL(string: "https://www.linkedin.com/in/vasileios-gkoumas-17073b236/")
    )

    static let about = AboutInfo(
        bio: [
            "I build my own apps so I don’t have to pay for anyone else’s.",
            "Hi! I’m an iOS developer passionate about crafting apps that feel native, fast, and beautiful. I care about the details — animations, accessibility, and architecture.",
            "When I’m not shipping features, I’m exploring new Apple frameworks, contributing to side projects, and refining my design sense.",
        ],
        education: [
            Education(
                school: "Harokopio University of Athens",
                degree: "B.Sc. in Computer Science",
                period: "October 2021 — September 2026"
            ),
        ]
    )

    static let experience: [ExperienceItem] = [
        ExperienceItem(
            role: "Bartender",
            company: "Lazy Athens",
            period: "May 2026 — Present",
            location: "Athens, Greece",
            bullets: []
        ),
    ]

    static let projects: [Project] = [
        Project(
            name: "Thesis: Surveilling Critical Infrastructure with LLMs",
            description: "Using large language models to monitor, analyze, and detect threats across critical infrastructure. An iOS application for citizens to report incidents. Using LLMs for object detection in images and analyzing. Learnt a lot about LLM training and fine tuning.",
            tech: ["SwiftUI", "LLMs", "Python", "Machine Learning", "CoreML"],
            githubUrl: nil,
            appStoreUrl: nil,
            appStoreStatus: nil
        ),
        Project(
            name: "Atelier",
            description: "An AI personal stylist for your wardrobe. Catalog your closet, then get weather-aware outfit suggestions generated by Claude, plan trip packing lists, and track wear insights.",
            tech: ["SwiftUI", "SwiftData", "StoreKit 2", "Vision", "Claude API"],
            githubUrl: nil,
            appStoreUrl: nil,
            appStoreStatus: "Expected on the App Store — Q4 2026"
        ),
        Project(
            name: "EvaluDate",
            description: "A private, on-device daily journaling and self-tracking app. Log mood, energy, sleep, water, and habits, then get AI-generated reflections, weekly/monthly reviews, and trend insights — all stored locally with SwiftData.",
            tech: ["SwiftUI", "SwiftData", "Swift Charts", "HealthKit", "Claude API"],
            githubUrl: URL(string: "https://github.com/YungN3O/EvaluDate"),
            appStoreUrl: nil,
            appStoreStatus: nil
        ),
    ]

    static let skills: [SkillCategory] = [
        SkillCategory(category: "Languages", items: [
            Skill(name: "Swift", level: 95),
            Skill(name: "Python", level: 40),
            Skill(name: "JavaScript / TypeScript", level: 60),
        ]),
        SkillCategory(category: "Frameworks", items: [
            Skill(name: "SwiftUI", level: 92),
            Skill(name: "SwiftData", level: 88),
            Skill(name: "Foundation Models", level: 80),
            Skill(name: "CoreML", level: 60),
        ]),
        SkillCategory(category: "Tools & Platforms", items: [
            Skill(name: "Xcode", level: 95),
            Skill(name: "Git", level: 90),
            Skill(name: "Claude Code", level: 88),
            Skill(name: "Prompt Engineering", level: 75),
        ]),
    ]
}
